name:                Animations
version:             0.1.0.0
github:              "githubuser/Animations"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Animations#readme>

dependencies:
- base >= 4.7 && < 5
- gloss
- not-gloss
- linear
- spatial-math

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Lines-exe:
    main:         Main.hs
    source-dirs:  app/Lines
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations

  Disk-and-circle-exe:
    main:         Main.hs
    source-dirs:  app/DiskAndCircle
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations

  Simple-disk-exe:
    main:         Main.hs
    source-dirs:  app/SimpleDisk
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations

  Projectile-exe:
    main:         Main.hs
    source-dirs:  app/Projectile
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations

  Blue-cube-exe:
    main:         Main.hs
    source-dirs:  app/BlueCube
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations

  Coordinate-system-exe:
    main:         Main.hs
    source-dirs:  app/CoordinateSystem
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations
  
  Rotating-cube-exe:
    main:         Main.hs
    source-dirs:  app/RotatingCube
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations
  
  ThreeD-simulation-exe:
    main:         Main.hs
    source-dirs:  app/ThreeDSimulation
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - Animations

tests:
  Animations-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Animations
